Feature/prepare nullsafe
icapps/flutter-icapps-translations pull request #29
Opened 2021-03-04 19:53 UTC by vanlooverenkoen

Fixed #27

2021-03-04 20:23 UTC, NicolaChimerapps requested changes

2021-03-04 20:23 UTC, NicolaChimerapps commented on example/ios/Flutter/Flutter.podspec
> +#       This is a generated file; do not edit or check into version control.
This may be a clue...

2021-03-04 21:21 UTC, vanlooverenkoen commented on example/ios/Flutter/Flutter.podspec
> +#       This is a generated file; do not edit or check into version control.
:D hahaah

2021-03-05 07:24 UTC, NicolaChimerapps approved these changes

2021-03-05 07:24 UTC, merged