Support new tool
icapps/flutter-icapps-translations pull request #38
Opened 2022-01-10 13:03 UTC by NicolaVerbeeck

Reworked code for better code reuse

2022-01-10 13:07 UTC, vanlooverenkoen requested changes

2022-01-10 13:07 UTC, vanlooverenkoen commented on bin/src/implementation/json_translation_downloader.dart
> +abstract class JSonTranslationDownloader
JsonTranslationDownloader?

2022-01-10 13:07 UTC, vanlooverenkoen commented on README.md
> +  project_id: 'optional project id' #To use the new translations tool, enter the project id here
I would add the `project_id` below the `api_key`

And maybe we should also mark all the required fields

2022-01-10 14:36 UTC, vanlooverenkoen approved these changes

2022-01-10 14:37 UTC, merged

2022-01-11 09:14 UTC, ikbendewilliam commented on bin/src/params.dart
> +    if (_projectId == null || _projectId?.isEmpty == true) {
either `_projectId == null || _projectId!.isEmpty == true` or `_projectId?.isNotEmpty != false`